log_message: "Sector mapping"
file_prefix: "sector"
code_key: "#sector +code +acronym"
name_key: "#sector +name +preferred +i_en"

datasetinfo:
  dataset: "global-coordination-groups-beta"
  resource: "Global Coordination Groups (Beta) CSV"
  format: "csv"
  headers: 2

extra_entries:
  "Cash": "Cash programming"
  "Hum": "Humanitarian assistance (unspecified)"
  "Multi": "Multi-sector (unspecified)"
  "Intersectoral": "Intersectoral"


initial_lookup:
  abna: "SHL"
  abri: "SHL"
  abri bna: "SHL"
  abris: "SHL"
  abris ame: "SHL"
  abris bna: "SHL"
  abris bna cccm: "SHL"
  abris durgence et nfi: "SHL"
  abris nfi: "SHL"
  action contre les mines: "PRO-MIN"
  aee: "SHL"
  agr: "FSC"
  agriculture: "FSC"
  agua saneamiento e higiene: "WSH"
  all: "Intersectoral"
  alojamiento de emergencia: "SHL"
  alojamiento de emergencia shelter: "SHL"
  alojamiento energ√≠a y enseres: "SHL"
  alojamientos y asentamientos: "SHL"
  ame: "SHL"
  ash: "WSH"
  assainissement: "WSH"
  basic assistance: "Cash"
  camp coordination and camp management: "CCM"
  camp coordination camp management: "CCM"
  cash: "Cash"
  cccm: "CCM"
  ccs: "CCM"
  cluster coordination: "CCM"
  coord services support: "CCM"
  coordinacion informacion: "CCM"
  coord support services: "CCM"
  coordination: "CCM"
  coordination et gestion des camps: "CCM"
  cp: "PRO-CPN"
  css: "CCM"
  eah: "WSH"
  eau: "WSH"
  eau assainissement et hygiene: "WSH"
  eau hygiene: "WSH"
  eau hygiene assainissement: "WSH"
  eau hygiene et assainissement: "WSH"
  educacion: "EDU"
  educacion en emergencias: "EDU"
  education: "EDU"
  efectivo multiproposito: "Cash"
  eha: "WSH"
  emergency shelter and non food items: "SHL"
  epah: "WSH"
  erl: "ERY"
  esnfi: "SHL"
  ets: "TEL"
  explosive hazards: "PRO-MIN"
  fss: "FSC"
  food: "FSC"
  food safety: "FSC"
  food security and agriculture: "FSC"
  food security and livelihoods: "FSC"
  food security and nutrition: "FSC"
  food security livelihood: "FSC"
  formation professionnelle: "EDU"
  fsl: "FSC"
  gestion des sites daccueil temporaires: "SHL"
  gbv: "PRO-GBV"
  general protection: "PRO"
  global protection: "PRO"
  hlp: "PRO-HLP"
  housing land property: "PRO-HLP"
  humanitaire: "Hum"
  hygiene: "WSH"
  hygiene assainissement: "WSH"
  intercluster: "Multi"  # From Somalia 3W, hopefully not to be confused with intersectoral
  logement terre et biens: "PRO-HLP"
  logistica: "LOG"
  logistique: "LOG"
  lutte contre la traite: "PRO-GBV"
  ma: "PRO-MIN"
  manejo y gestion de campamentos: "CCM"
  migrant protection: "PRO"
  mpc: "Cash"
  mpca: "Cash"
  ms: "Multi"
  multi purpose cash: "Cash"
  multi secteur: "Multi"
  multisectoriel: "Multi"
  nutricion: "NUT"
  nutrition: "NUT"
  operatioanl presence water sanitation hygiene: "WSH"
  operational presence education in emergencies: "EDU"
  operational presence emergency shelter non food items: "SHL"
  operational presence food security agriculture: "FSC"
  operational presence health: "HEA"
  operational presence nutrition: "NUT"
  operational presence protection: "PRO"
  pro cpm: "PRO-CPN"
  pronna: "PRO-CPN"
  propg: "PRO"
  proteccion infantil: "PRO-CPN"
  proteccion ninos ninas adolescentes: "PRO-CPN"
  proteccion violencia de genero: "PRO-GBV"
  protection: "PRO"
  protection de lenfance: "PRO-CPN"
  protection de lenfant: "PRO-CPN"
  protection generale: "PRO"
  protection logement terre et propriete: "PRO-HLP"
  protection ltb: "PRO-HLP"
  protection lutte anti mines: "PRO-MIN"
  protection pe: "PRO-CPN"
  protection protection de lenfant: "PRO-CPN"
  protection violences basees sur le genre: "PRO-GBV"
  protection vgb: "PRO-GBV"
  proteccion: "PRO"
  provbg: "PRO-GBV"
  psea: "PRO-GBV"
  rapid response mechanism: "ERY"
  rcf: "CCM"
  rcf education: "EDU"
  rcf food security and livelihoods: "FSC"
  rcf health and nutrtion: "HEA"
  rcf protection: "PRO"
  recuperacion temprana: "ERY"
  relevement precoce: "ERY"
  relevement rapide: "ERY"
  refugees: "CCM"
  refugee response: "CCM"
  refugees migrants multi sector: "CCM"
  reponse aux refugies: "CCM"
  sa: "FSC"
  sal: "HEA"
  salud: "HEA"
  same: "FSC"
  samv: "FSC"
  sante: "HEA"
  securite alimentaire: "FSC"
  securite alimentaire et moyen dexistence: "FSC"
  seguridad alimentaria: "FSC"
  seguridad alimentaria y nutricion: "FSC"
  services humanitaires communs: "Hum"
  sexual and reproductive health: "HEA"
  shelter: "SHL"
  shelter nfi: "SHL"
  shelter nfis: "SHL"
  shelter and nfi: "SHL"
  shelter and nfis: "SHL"
  shelter and non food items: "SHL"
  shelter site coordination: "SHL"
  site management: "CCM"
  snfi: "SHL"
  sspe: "PRO-CPN"
  telecommunications: "TEL"
  telecommunications durgence: "TEL"
  telecomunicaciones de emergencia: "TEL"
  transversal: "Multi"
  vbg: "PRO-GBV"
  violences basees sur le genre: "PRO-GBV"
  violence basee sur le genre: "PRO-GBV"
  violencia basada en genero: "PRO-GBV"
  wash: "WSH"
  water sanitation and hygiene: "WSH"
